version: '3.8'

services:
  3wallet-prod1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_ETHEREUM_RPC=${NEXT_PUBLIC_ETHEREUM_RPC}
      - NEXT_PUBLIC_BITCOIN_API=${NEXT_PUBLIC_BITCOIN_API}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

