version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - 3wallet-network

networks:
  3wallet-network:
    driver: bridge

